import type { HistoricalEvent } from "@/lib/content/schemas";

export const historicalEvents: HistoricalEvent[] = [
  {
    id: "early-settlements",
    title: "Early settlements",
    period: "Before c. 2600 BCE",
    startYear: -7000,
    endYear: -2600,
    precision: "range",
    summary: "Archaeological evidence records diverse early communities and changing food-producing systems.",
    sourceIds: ["ncert-history"],
    confidence: "medium",
  },
  {
    id: "indus-cities",
    title: "Indus cities",
    period: "c. 2600–1900 BCE",
    startYear: -2600,
    endYear: -1900,
    precision: "approximate",
    summary: "Urban centres, craft production and long-distance exchange developed across the northwestern subcontinent.",
    sourceIds: ["ncert-history"],
    confidence: "high",
  },
  {
    id: "mauryan-networks",
    title: "Mauryan networks",
    period: "c. 322–185 BCE",
    startYear: -322,
    endYear: -185,
    precision: "approximate",
    summary: "Inscriptions, settlements and routes provide evidence for a wide imperial formation and regional administration.",
    sourceIds: ["ncert-history"],
    confidence: "high",
  },
  {
    id: "classical-worlds",
    title: "Classical worlds",
    period: "c. 200 BCE–600 CE",
    startYear: -200,
    endYear: 600,
    precision: "range",
    summary: "Regional states, trade, literature, art and scientific traditions developed through overlapping networks.",
    sourceIds: ["ncert-history"],
    confidence: "medium",
  },
  {
    id: "regional-kingdoms",
    title: "Regional kingdoms",
    period: "c. 600–1200 CE",
    startYear: 600,
    endYear: 1200,
    precision: "range",
    summary: "Political centres and cultural forms changed across many regional courts, communities and landscapes.",
    sourceIds: ["ncert-history"],
    confidence: "medium",
  },
  {
    id: "sultanates",
    title: "Sultanates",
    period: "c. 1200–1526 CE",
    startYear: 1200,
    endYear: 1526,
    precision: "approximate",
    summary: "New political formations interacted with existing regional powers, commercial networks and urban cultures.",
    sourceIds: ["ncert-history"],
    confidence: "high",
  },
  {
    id: "mughal-era",
    title: "Mughal era",
    period: "1526–1857 CE",
    startYear: 1526,
    endYear: 1857,
    precision: "range",
    summary: "Imperial institutions, regional powers, agrarian systems and artistic exchange changed over three centuries.",
    sourceIds: ["ncert-history"],
    confidence: "high",
  },
  {
    id: "colonial-rule",
    title: "Colonial rule",
    period: "c. 1757–1947 CE",
    startYear: 1757,
    endYear: 1947,
    precision: "approximate",
    summary: "Company and Crown rule transformed political authority, economy, infrastructure and social movements unevenly.",
    sourceIds: ["ncert-history"],
    confidence: "high",
  },
  {
    id: "independence",
    title: "Independence",
    period: "1947 CE",
    startYear: 1947,
    precision: "exact",
    summary: "British colonial rule ended in 1947 amid independence, Partition and large-scale displacement.",
    sourceIds: ["ncert-history"],
    confidence: "high",
  },
  {
    id: "republic",
    title: "Republic of India",
    period: "1950–present",
    startYear: 1950,
    precision: "range",
    summary: "The Constitution came into force in 1950; contemporary India continues to change through democratic, social, scientific and economic life.",
    sourceIds: ["ncert-history"],
    confidence: "high",
  },
];
