import type { Source } from "@/lib/content/schemas";

export const sources: Source[] = [
  {
    id: "census-tables-2011",
    title: "Census of India 2011 — Data tables",
    publisher: "Office of the Registrar General & Census Commissioner, India",
    url: "https://censusindia.gov.in/census.website/en/data/tables",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
    note: "Primary Census Abstract and literacy tables used for Phase 1 state comparisons.",
  },
  {
    id: "census-population-finder",
    title: "Population Finder — Census 2011",
    publisher: "Office of the Registrar General & Census Commissioner, India",
    url: "https://censusindia.gov.in/census.website/en/data/population-finder",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "odisha-topography",
    title: "Topography of Odisha",
    publisher: "Government of Odisha",
    url: "https://odisha.gov.in/en/odisha-profile/topography",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "rajasthan-geography",
    title: "Geographic Profile of Rajasthan",
    publisher: "Office of the Resident Commissioner, Government of Rajasthan",
    url: "https://rc.rajasthan.gov.in/gographicprofile.aspx",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "rajasthan-physiography",
    title: "Physiography of Rajasthan",
    publisher: "Rajasthan State Biodiversity Board",
    url: "https://environment.rajasthan.gov.in/content/environment/en/rsbb/about-rajasthan/physiography-of-rajasthan.html",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "kerala-state-profile",
    title: "Kerala State Profile",
    publisher: "Chief Electoral Officer, Kerala",
    url: "https://webapp.ceo.kerala.gov.in/stateprofile.html",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "isro-profile",
    title: "About ISRO",
    publisher: "Indian Space Research Organisation",
    url: "https://www.isro.gov.in/ISRO_EN/profile.html",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "isro-vision",
    title: "Vision, Mission and Objectives",
    publisher: "Indian Space Research Organisation",
    url: "https://www.isro.gov.in/Vision-Mission-Objectives.html",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "unesco-india",
    title: "India — World Heritage Convention",
    publisher: "UNESCO",
    url: "https://whc.unesco.org/en/statesparties/in",
    sourceType: "institutional",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "unesco-intangible-india",
    title: "India — Intangible Cultural Heritage",
    publisher: "UNESCO",
    url: "https://ich.unesco.org/en/state/india-IN?info=elements-on-the-lists",
    sourceType: "institutional",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "geoboundaries-ind-adm1",
    title: "India ADM1 administrative boundaries",
    publisher: "geoBoundaries",
    url: "https://www.geoboundaries.org/api/current/gbOpen/IND/ADM1/",
    sourceType: "academic",
    license: "Creative Commons Attribution 2.5 India (CC BY 2.5 IN)",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
    note: "Source attribution lists DataMeet India community and Election Commission of India.",
  },
  {
    id: "imd-monsoon",
    title: "Monsoon Information",
    publisher: "India Meteorological Department",
    url: "https://mausam.imd.gov.in/responsive/monsooninformation.php",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "cwc-river-basins",
    title: "River Basins of India",
    publisher: "Central Water Commission",
    url: "https://cwc.gov.in/river-basins",
    sourceType: "primary",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "ncert-history",
    title: "NCERT History Textbooks",
    publisher: "National Council of Educational Research and Training",
    url: "https://ncert.nic.in/textbook.php",
    sourceType: "institutional",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
  {
    id: "st-andrews-indian-numerals",
    title: "Indian numerals",
    publisher: "MacTutor History of Mathematics, University of St Andrews",
    url: "https://mathshistory.st-andrews.ac.uk/HistTopics/Indian_numerals/",
    sourceType: "academic",
    accessedAt: "2026-07-29",
    reviewedAt: "2026-07-29",
  },
];

export const sourceById = new Map(sources.map((source) => [source.id, source]));
