export const siteConfig = {
  name: "BHARAT",
  devanagariName: "भारत",
  title: "BHARAT — A living atlas of a civilization",
  description: "Explore the land, people, history, ideas and future of India.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://bharat-atlas.vercel.app",
  repository: "https://github.com/SatyajitBeura2468/bharat",
  locale: "en_IN",
} as const;

export const primaryNavigation = [
  { label: "Explore", href: "/explore" },
  { label: "History", href: "/history" },
  { label: "Culture", href: "/culture" },
  { label: "Nature", href: "/nature" },
  { label: "Innovation", href: "/innovation" },
  { label: "Data", href: "/data" },
  { label: "Stories", href: "/stories" },
] as const;

export const allRoutes = [
  "/",
  "/explore",
  "/states",
  "/states/odisha",
  "/states/rajasthan",
  "/states/kerala",
  "/places/chilika-lake",
  "/places/thar-desert",
  "/places/western-ghats",
  "/history",
  "/history/timeline",
  "/culture",
  "/nature",
  "/innovation",
  "/innovation/space",
  "/data",
  "/stories",
  "/stories/how-the-monsoon-shapes-india",
  "/stories/indias-languages-and-scripts",
  "/stories/the-story-of-zero",
  "/stories/the-indian-space-programme",
  "/stories/rivers-that-shaped-civilisation",
  "/stories/architecture-across-regions",
  "/search",
  "/sources",
  "/methodology",
  "/about",
] as const;
